#Requires -Version 7.0
<#
.SYNOPSIS
    Emit the mapping tables for the vault note, in Obsidian-flavoured Markdown.

.DESCRIPTION
    The third consumer of unixmap.psd1, and the one the manifest exists for.
    Shims, unixhelp and a hand-written note documenting both is three copies
    that disagree within a month; this makes the note's tables a build product
    of the same file the shims load.

    Output goes to stdout and is pasted between the generated-region markers in
    Resources/Shell/PowerShell/PowerShell for zsh Users.md. It is NOT written
    to a path in this repo: the vault is private and this repo is public, so
    the file path stays on the vault side of the line.

    Markdown here follows the vault's conventions rather than this repo's:
    tight lists, a blank line before every table, no wikilinks (the narrative
    around the generated region owns those, so regenerating cannot break a
    link), and pipes escaped inside cells. The region markers are Obsidian
    comments — %% .. %% — not HTML ones: Obsidian renders raw HTML, so
    anything in angle brackets is a tag, and the surest way to make text
    vanish from a note is to write it between them.

.EXAMPLE
    pwsh -File tools/Build-VaultTable.ps1 | pbcopy
#>
[CmdletBinding()]
param(
    [string]$ManifestPath  = (Join-Path $PSScriptRoot '..' 'unixmap.psd1'),
    [string]$GeneratedPath = (Join-Path $PSScriptRoot '..' 'generated-aliases.ps1')
)

$ErrorActionPreference = 'Stop'
$manifest = Import-PowerShellDataFile -LiteralPath $ManifestPath

# A cell containing an unescaped pipe silently truncates the row, and a `[[x]]`
# or `#word` in a cell becomes a live link or a tag in the vault. Backtick the
# hash; escape the pipe.
function Format-Cell {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return '—' }
    $Text.Replace('|', '\|').Replace('#', '`#`')
}

# The alias counts come from the artifact rather than from the manifest, so the
# note cannot claim a number the shipped file does not have — and they are read
# with the PARSER, not a regex. A regex on `^function ` undercounts by one,
# because one of the ported names is a Set-Alias rather than a function, and it
# cannot see the shadowed array at all.
$genAst = [System.Management.Automation.Language.Parser]::ParseFile(
    (Resolve-Path -LiteralPath $GeneratedPath), [ref]$null, [ref]$null)

$functions = $genAst.FindAll({
        $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
$aliasCmds = $genAst.FindAll({
        $args[0] -is [System.Management.Automation.Language.CommandAst] -and
        $args[0].GetCommandName() -in @('Set-Alias', 'New-Alias') }, $true)
$aliasCount = $functions.Count + $aliasCmds.Count

$shadowAssign = $genAst.FindAll({
        $args[0] -is [System.Management.Automation.Language.AssignmentStatementAst] -and
        $args[0].Left.Extent.Text -eq '$script:PSParityShadowed' }, $true) | Select-Object -First 1
$shadowCount = if ($shadowAssign) {
    @($shadowAssign.Right.FindAll({
        $args[0] -is [System.Management.Automation.Language.HashtableAst] }, $true)).Count
} else { 0 }

$out = [System.Text.StringBuilder]::new()
function Add-Line { param([string]$Text = '') [void]$out.AppendLine($Text) }

Add-Line "%% generated by powershell/tools/Build-VaultTable.ps1 — edit unixmap.psd1, not this region %%"
Add-Line "### The shape of the port"
# A table with no blank line above it gets absorbed into the preceding block by
# Obsidian and renders as raw pipes. That holds even directly under a heading.
Add-Line ''
Add-Line "| Category | Count | Where it lives |"
Add-Line "| -------- | ----- | -------------- |"
Add-Line "| Generated git aliases | $aliasCount | ``generated-aliases.ps1`` |"
Add-Line "| Hand-written shims | $($manifest.Shims.Count) | ``functions/*.ps1`` |"
Add-Line "| Not ported, with a reason | $($manifest.NotPorted.Count) entries | the manifest |"
Add-Line "| Unreachable by case collision | $shadowCount | emitted as data, so ``unixhelp`` can explain them |"
Add-Line "| Built-ins displaced | $($manifest.Collisions.Count) | ``Remove-Alias`` before each definition |"
Add-Line "| Built-in traps left alone | $($manifest.Traps.Count) | listed, not overridden |"

Add-Line "### Tier B — the shims"
Add-Line "Written by hand because they need arguments, and a PowerShell alias is a name-to-name mapping that cannot carry any."
Add-Line ''
Add-Line "| Command | Needs | File | What it does |"
Add-Line "| ------- | ----- | ---- | ------------ |"
foreach ($s in $manifest.Shims) {
    $req = if ($s.Requires) { "``$($s.Requires)``" } else { '—' }
    Add-Line "| ``$($s.Name)`` | $req | ``$($s.File)`` | $(Format-Cell $s.Note) |"
}

Add-Line "### Tier C — not ported, and why"
Add-Line "The half that usually gets dropped in silence. ``unixhelp <name>`` answers with the reason instead."
Add-Line ''
Add-Line "| zsh | Why not | Reach for instead |"
Add-Line "| --- | ------- | ----------------- |"
foreach ($n in $manifest.NotPorted) {
    Add-Line "| ``$($n.Name)`` | $(Format-Cell $n.Reason) | $(Format-Cell $n.Instead) |"
}

Add-Line "### Built-ins that mean something else"
Add-Line "Not overridden — the PowerShell meaning is the right one here. Listed because the failure is silent and the name is familiar."
Add-Line ''
Add-Line "| Name | Really is | The trap |"
Add-Line "| ---- | --------- | -------- |"
foreach ($t in $manifest.Traps) {
    Add-Line "| ``$($t.Name)`` | ``$($t.Is)`` | $(Format-Cell $t.Note) |"
}

Add-Line "### Idioms"
Add-Line "What a zsh user needs to know that no alias table can express. ``unixhelp -Idioms`` prints these at the prompt."
Add-Line ''
Add-Line "| Topic | The point | Detail |"
Add-Line "| ----- | --------- | ------ |"
foreach ($i in $manifest.Idioms) {
    Add-Line "| ``$($i.Topic)`` | $(Format-Cell $i.Summary) | $(Format-Cell $i.Detail) |"
}

Add-Line "### Packages"
Add-Line "Six verbs, not a mirror of the 28 ``brew``/``cask`` aliases — enough to build a CLI habit where the habit so far has been a GUI updater."
Add-Line ''
Add-Line "| Alias | Runs | Note |"
Add-Line "| ----- | ---- | ---- |"
foreach ($p in $manifest.Packages) {
    Add-Line "| ``$($p.Name)`` | ``$($p.Runs)`` | $(Format-Cell $p.Note) |"
}

$installed = @($manifest.Tools | Where-Object { $_.Install })
$considered = @($manifest.Tools | Where-Object { -not $_.Install })
Add-Line "### The tools the shims assume"
Add-Line "``bootstrap.ps1`` installs these; ``winget.json`` declares the same set for a standalone ``winget import``."
Add-Line ''
Add-Line "| Tool | winget id | Provides |"
Add-Line "| ---- | --------- | -------- |"
foreach ($t in $installed) {
    $prov = if ($t.Provides) { ($t.Provides | ForEach-Object { "``$_``" }) -join ', ' } else { '—' }
    Add-Line "| ``$($t.Name)`` | ``$($t.WingetId)`` | $prov |"
}
$consideredList = ($considered | ForEach-Object { '`' + $_.Name + '`' }) -join ', '
Add-Line "Considered and not installed: $consideredList."
Add-Line "%% end generated region %%"

$out.ToString().TrimEnd() -replace "`r`n", "`n"
