#!/usr/bin/env zsh
#
# dump-aliases.zsh — capture the live zsh alias set for the PowerShell port.
#
# Run this on the Mac, commit the result, then run Build-Aliases.ps1 anywhere
# pwsh exists. The two halves are split because the aliases only exist on macOS
# and the generator only runs under PowerShell, and no machine has both.
#
# Why a live dump rather than reading the repo: only ~58 of 225 aliases are
# authored here. Zim's git and homebrew modules synthesise the other 167 at
# shell start, so the running shell is the inventory, not the files.
#
#   ./dump-aliases.zsh            # write ../zsh-aliases.dump
#   ./dump-aliases.zsh -o -       # write to stdout
#
set -euo pipefail

out="${0:A:h}/../zsh-aliases.dump"
[[ "${1:-}" == "-o" ]] && out="${2:-}"

# SSH host shortcuts are redacted: they carry internal hostnames and this repo
# is public. They are classified tier C by name in unixmap.psd1 regardless, so
# nothing downstream depends on seeing them here.
redact='^(nas|nuc|pihole|pi-hole)='

dump="$(zsh -ic 'alias' 2>/dev/null)"
kept="$(print -r -- "$dump"   | grep -Ev "$redact" || true)"
n_all=$(print -r -- "$dump"   | grep -c . || true)
n_kept=$(print -r -- "$kept"  | grep -c . || true)

body="# Generated by tools/dump-aliases.zsh — do not edit.
# Source: zsh -ic alias
# ${n_kept} of ${n_all} aliases; $(( n_all - n_kept )) SSH host shortcuts redacted.
${kept}"

if [[ "$out" == "-" ]]; then
  print -r -- "$body"
else
  print -r -- "$body" > "$out"
  print -r -- "wrote ${n_kept} aliases to ${out:A}"
fi
