#!/usr/bin/env zsh

export CCHOME='/home/dev/Source/cc'

alias cdcc='cd /opt/ocedo'

cpcc() {
    cp /opt/ocedo/etc/CC*.pem ~/Source/cc/etc
    cp /opt/ocedo/etc/gui-cert.pem ~/Source/cc/etc
    cp /opt/ocedo/etc/gui-chain.pem ~/Source/cc/etc
    cp /opt/ocedo/etc/gui-key.pem ~/Source/cc/etc
    cp /opt/ocedo/etc/cc.config ~/Source/cc/etc
}

run-dev() {
    cd $CCHOME  && bin/ccctl run-dev
}