#!/usr/local/bin/zsh

alias love="/Applications/love.app/Contents/MacOS/love"
alias mcs='/Users/dale/Minecraft/run_minecraft_server.sh'
alias ts='"/Applications/TeamSpeak 3 Client.app/Contents/MacOS/ts3client_mac" -nosingleinstance'

findbook() {
    mdfind -name "$1" -onlyin '/Volumes/Retina External/Books'
}

# Fix enter on numeric keypad in iTerm 2 with zsh
bindkey -s "^[OM" "^M"

rbenv shell 2.3.0
