#!/usr/bin/env zsh

function ssh-to {
	bat $1;
	echo -e "\033]6;1;bg;red;brightness;209\a"
	echo -e "\033]6;1;bg;green;brightness;209\a"
	echo -e "\033]6;1;bg;blue;brightness;254\a"
	ssh $2;
	bat ""
	echo -e "\033]6;1;bg;*;default\a"
}

function devcc-root {
    ssh-to 'devcc!' root@10.5.108.203
}

function devcc {
    ssh-to devcc dev@10.5.108.203
}

function dale-cheetah {
    ssh-to cheetah root@10.5.108.72
}

function dale-tiger {
    ssh-to tiger root@10.5.108.149
}

function picrite {
    ssh-to picrite ddavis@picrite.lab.nbttech.com
}

# Create a git repo at specified location. Ex: mkgit foo gmail <= use personal github email
function mkgit {
	local $folder=$1
	mkdir $folder
	cd $folder
	git init
	if [ $2 == "gmail" ]; then
		githubmail
	fi
}

alias bento="$HOME/Source/github/chef/bento/bin/bento"

rbenv shell 2.3.0
