#Requires -Version 7.0
<#
.SYNOPSIS
    Bring a Windows machine up to this repo's PowerShell configuration.

.DESCRIPTION
    Idempotent by design: it reports what it CHANGED, not what it did. A second
    run on a configured machine should report zero changes, and that property is
    the point — it makes the script safe to re-run after any drift, and makes
    "measure the change, don't assume it" possible.

    Four steps, each skippable:

      1. winget packages from unixmap.psd1 (Install = $true only)
      2. PowerShell modules from unixmap.psd1
      3. the $PROFILE stub pointing at this repo
      4. a summary of what actually changed

    Nothing here is destructive. It installs and it writes one small stub; it
    never removes a package, and it will not overwrite an existing stub that
    already points at the right place.

.PARAMETER WhatIf
    Report the plan without installing anything. Run this first.

.EXAMPLE
    pwsh -File bootstrap.ps1 -WhatIf
.EXAMPLE
    pwsh -File bootstrap.ps1
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$ManifestPath = (Join-Path $PSScriptRoot 'unixmap.psd1'),
    [switch]$SkipPackages,
    [switch]$SkipModules,
    [switch]$SkipProfile
)

$ErrorActionPreference = 'Stop'

if (-not $IsWindows) {
    Write-Error 'bootstrap.ps1 configures a Windows machine. On macOS the repo is stowed by the install script instead.'
    exit 2
}

$manifest = Import-PowerShellDataFile -LiteralPath $ManifestPath
$changed  = [System.Collections.Generic.List[string]]::new()
$skipped  = [System.Collections.Generic.List[string]]::new()
$failed   = [System.Collections.Generic.List[string]]::new()

# --- 1. winget packages ---------------------------------------------------
if (-not $SkipPackages) {
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        $failed.Add('winget is not on PATH; skipping all package installs')
    } else {
        foreach ($tool in ($manifest.Tools | Where-Object { $_.Install })) {
            # Ask winget, not the PATH. A tool can be installed and not yet on
            # PATH in this session, and reinstalling it would be a no-op that
            # still costs a network round trip and muddies the change report.
            $listed = winget list --exact --id $tool.WingetId --disable-interactivity 2>&1 | Out-String
            if ($listed -notmatch 'No installed package found') {
                $skipped.Add("package $($tool.Name) — already installed")
                continue
            }

            if ($PSCmdlet.ShouldProcess($tool.WingetId, 'winget install')) {
                # Captured rather than streamed: winget is chatty and this runs
                # over SSH, where stray output corrupts structured results. The
                # capture is not thrown away — its last line is the useful part
                # of a failure, and an exit code alone rarely says why.
                $out = winget install --exact --id $tool.WingetId `
                    --accept-package-agreements --accept-source-agreements `
                    --disable-interactivity 2>&1 | Out-String
                if ($LASTEXITCODE -eq 0) {
                    $changed.Add("installed $($tool.Name) ($($tool.WingetId))")
                } else {
                    $tail = ($out.Trim() -split "`n" | Where-Object { $_.Trim() } | Select-Object -Last 1)
                    $failed.Add("$($tool.Name): winget exit $LASTEXITCODE — $($tail.Trim())")
                }
            } else {
                $changed.Add("WOULD install $($tool.Name) ($($tool.WingetId))")
            }
        }
    }
}

# --- 2. PowerShell modules ------------------------------------------------
if (-not $SkipModules) {
    foreach ($mod in ($manifest.Modules | Where-Object { $_.Install })) {
        $have = Get-Module -ListAvailable -Name $mod.Name |
                Sort-Object Version -Descending | Select-Object -First 1
        if ($have) {
            $skipped.Add("module $($mod.Name) — already at $($have.Version)")
            continue
        }
        if ($PSCmdlet.ShouldProcess($mod.Name, 'Install-Module')) {
            try {
                Install-Module -Name $mod.Name -Scope CurrentUser -Force -AcceptLicense -ErrorAction Stop
                $changed.Add("installed module $($mod.Name)")
            } catch {
                $failed.Add("module $($mod.Name): $($_.Exception.Message)")
            }
        } else {
            $changed.Add("WOULD install module $($mod.Name)")
        }
    }
}

# --- 3. the $PROFILE stub -------------------------------------------------
if (-not $SkipProfile) {
    $repoProfile = Join-Path $PSScriptRoot 'profile.ps1'
    $stubPath    = $PROFILE.CurrentUserAllHosts
    $stubBody    = @"
# `$PROFILE stub — the real configuration lives in the dotfiles repo.
#
# DO NOT EDIT THIS FILE. Edit powershell/profile.ps1 in the repo and commit it.
# Written by powershell/bootstrap.ps1.

`$parityProfile = '$repoProfile'
if (Test-Path -LiteralPath `$parityProfile) { . `$parityProfile }
"@

    $existing = if (Test-Path -LiteralPath $stubPath) { Get-Content -LiteralPath $stubPath -Raw } else { $null }
    if ($existing -and $existing -match [regex]::Escape($repoProfile)) {
        $skipped.Add('profile stub — already points at this repo')
    } elseif ($PSCmdlet.ShouldProcess($stubPath, 'write $PROFILE stub')) {
        New-Item -ItemType Directory -Force -Path (Split-Path $stubPath -Parent) | Out-Null
        if ($existing) {
            # Never clobber a profile that is not ours without keeping a copy.
            $backup = "$stubPath.bak-$(Get-Date -Format 'yyyy-MM-dd')"
            if (-not (Test-Path -LiteralPath $backup)) { Copy-Item -LiteralPath $stubPath -Destination $backup }
            $changed.Add("backed up existing profile to $(Split-Path $backup -Leaf)")
        }
        [IO.File]::WriteAllText($stubPath, $stubBody, [System.Text.UTF8Encoding]::new($false))
        $changed.Add("wrote profile stub -> $stubPath")
    } else {
        $changed.Add("WOULD write profile stub -> $stubPath")
    }
}

[pscustomobject]@{
    Changed      = $changed.Count
    ChangedItems = @($changed)
    Skipped      = $skipped.Count
    SkippedItems = @($skipped)
    Failed       = $failed.Count
    FailedItems  = @($failed)
}
