#!/usr/bin/env zsh

HISTSIZE=10000
SAVEHIST=10000

setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# Environment
ARCH=$(uname -m)
KERNEL=$(uname -r)
if [ -f /etc/lsb-release ]; then
    OS=$(lsb_release -s -d)
elif [ -f /etc/debian_version ]; then
    OS="Debian $(cat /etc/debian_version)"
elif [ -f /etc/redhat-release ]; then
    OS=`cat /etc/redhat-release`
else
    OS="$(uname -s) $(uname -r)"
fi
export DOTFILES="$HOME/.files"
export DEFAULT_USER=`whoami`
export HOSTNAME=`hostname -s`
export PROJECT_HOME="$HOME/Source"
export TERM='xterm-256color'
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Teh fukc, d00d? Next time, try: "

# Load plugins
source "$DOTFILES/zgen/zgen.zsh"
if ! zgen saved; then
    print "Creating a zgen save"
    zgen prezto '*:*' case-sensitive 'yes'
	zgen prezto '*:*' color 'yes'
    zgen prezto
    zgen prezto 'environment'
    zgen prezto 'terminal'
    zgen prezto 'editor'
    zgen prezto 'history'
    zgen prezto 'spectrum'
    zgen prezto 'utility'
    zgen prezto 'completion'
    zgen prezto 'archive'
    zgen prezto 'terminal'
    zgen prezto 'fasd'
    zgen prezto 'rsync'
    zgen prezto 'git'
    zgen prezto 'ssh'
    zgen prezto 'ruby'
#    zgen prezto 'python'
    zgen prezto 'spectrum'
    # zgen prezto 'tmux' ## When current changes have stabilized
    # python, node, and perl are on you
    if [[ "$OS" == Darwin* ]]; then
        zgen prezto 'osx'
        zgen prezto 'homebrew'
        zgen load "$DOTFILES/osx"
    elif [[ "$OS" == Fedora* ]]; then
        zgen prezto 'yum'
    else  # Debian, Ubuntu, Linux Mint, and other apt-based distros
        zgen prezto 'dpkg'
        zgen prezto 'command-not-found'
    fi
    zgen oh-my-zsh plugins/cp
    zgen oh-my-zsh plugins/colorize
    zgen oh-my-zsh plugins/emoji-clock
    zgen oh-my-zsh plugins/colored-man-pages
    zgen oh-my-zsh plugins/rand-quote
    zgen oh-my-zsh plugins/fabric
    zgen oh-my-zsh plugins/vagrant
    zgen oh-my-zsh plugins/perl
    zgen oh-my-zsh plugins/cpanm
    zgen oh-my-zsh plugins/rbenv
    zgen oh-my-zsh plugins/osx
    zgen oh-my-zsh plugins/bre
    zgen oh-my-zsh plugins/forklift
    zgen oh-my-zsh plugins/textmate
    zgen load jocelynmallon/zshmarks
    zgen load Tarrasch/zsh-autoenv
    zgen load djui/alias-tips
    zgen load "$DOTFILES/git"
    zgen load "$DOTFILES/python"
    zgen load "$DOTFILES/vim"
    zgen load "$DOTFILES/perl"
    if [[ -s "/usr/local/bin/pyenv" ]]; then
        # pyenv's virtualenvwrapper
        zgen load "$DOTFILES/pyenv"
    else
        # pyenv shims don't support sourcing (it'll blow up zsh)
        # Only load this guy if you're not running pyenv
        zplug oh-my-zsh virtualenvwrapper
    fi
    zgen load bhilburn/powerlevel9k powerlevel9k
    zgen prezto 'syntax-highlighting'
    zgen prezto 'history-substring-search'
    zgen prezto 'prompt'
    zgen save
fi
# Probably prefer oh-my-zsh plenv or personal to prezto/perl

# date
alias gmt="date -u"
alias utc='date -u'

# cd/fasd
alias cd..='cd ..'
alias cd...='cd ...'
alias j='fasd_cd -d'

# ls
alias dir=ls
alias l='ls -CF'
alias lla="ll -a"
alias lld='ls -ld */'

# grep
alias fsize='du -ch | grep total'
alias hig='history | grep'
if (( $+commands[ag] )); then
    alias ack=`which ag`  # Silver Searcher > ack, but you can't teach old fingers new tricks
fi
alias ag='alias | grep'

# ruby
alias lsr="rbenv versions"

# copy/paste
alias pwdc="pwd | pbcopy"

# colorize/cat
alias ct='colorize'

# tmux
alias tls='tmux ls'

if [[ -f /etc/lsb-release ]]; then
    alias sysinfo='inxi -Fxz'
fi

# Conversion
function b2d() {
    echo $((2#$1))
}

function o2d() {
    echo $((8#$1))
}

function h2d() {
    echo $((16#$1))
}

# Search
function fid {
    find . -name $1 -print
}

# Recursive deletion of glob
function rmr {
    find . -name "$1" -exec rm '{}' ';'
}

# Set window/tab title
function title {
    echo -ne "\e]1;$1\a"
}

# Set iTerm3 badge
badge() {
    printf "\e]1337;SetBadgeFormat=%s\a" \
        $(echo -n "$1" | base64)
}

# Set (ba)dge and (t)itle
bat() {
    local msg=$1
    title $msg && badge $msg
}

_wt() {
    printf "$1$(date +"%I:%M %p")  $(emoji-clock)\n"
}

# Current time at various locations
function wt {
    echo
    echo "$fg[blue]===== Current Times =====$fg[default]"
    echo
    export TZ=US/Pacific
    _wt "San Jose:      "
    export TZ=America/Phoenix
    _wt "Phoenix:       "
    export TZ=US/Mountain
    _wt "Boise:         "
    _wt "Silver City:   "
    export TZ=US/Central
    _wt "Austin:        "
    export TZ=America/Toronto
    _wt "Toronto, CA:   "
    export TZ=UTC
    _wt "UTC:           "
    export TZ=Europe/Berlin
    _wt "Karlsruhe, DE: "
    export TZ=Asia/Kolkata
    _wt "Bangalore, IN: "
    # Don't forget to reset to local
    export TZ=US/Pacific
    echo
    echo "$fg[blue]=========================$fg[default]"
}

function upall {
    echo "$fg[blue][Updating zplug ZSH plugin framework]$fg[default]"
    zplug update
    if [[ -d $HOME/.vim/janus ]]; then
        echo "$fg[blue][Updating Janus VIM distribution]$fg[default]"
        jvu
    fi
    # TODO Add Python, Ruby, Perl, apt, brew, node, app store
}

# Show all 255 terminal colors and their codes
show-colors() {
    for code in {000..255}; do print -P -- "$code: %F{$code}Test%f"; done
}

if (( $+commands[ag] )); then
    eval $(thefuck --alias)
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Anonymous function to load machine-specific aliases and functions.
function {
    local host_specific_script="$DOTFILES/zsh/host-specific/$HOSTNAME"
    if [[ -e "$host_specific_script" ]]; then
        . $host_specific_script
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
